# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.box_check_update = false
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

	config.hostmanager.enabled = true
	config.hostmanager.manage_host = true
	config.hostmanager.manage_guest = true
	config.hostmanager.ignore_private_ip = false
	config.vbguest.auto_update = false

	# script de aprovisionamento común
	#config.vm.provision :shell, path: "bootstrap.sh"

	config.vm.define "master" do |master|
		master.vm.hostname = "master"
		master.vm.network :private_network, ip:"190.168.1.10"
	end

	config.vm.define "nodeOne" do |nodeOne|
		nodeOne.vm.hostname = "nodeOne"
		nodeOne.vm.network :private_network, ip:"190.168.1.11"
	end

	config.vm.define "nodeTwo" do |nodeTwo|
		nodeTwo.vm.hostname = "nodeTwo"
		nodeTwo.vm.network :private_network, ip:"190.168.1.12"
	end

	config.vm.provider :virtualbox do |vb|
    	vb.memory = "1024"
	end

end
